name:                GDHAPPI
version:             0.0.0.1
github:              "Vawlpe/GDHAPPI"
license:             GPL-3
author:              "Hazel (Vawlpe)"
maintainer:          "vawlpe@gmail.com"
copyright:           "2022 Hazel (Vawlpe)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/GDHAPPI#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- network
- cpu
- hosc

library:
  source-dirs: src

executables:
  GDHAPPI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GDHAPPI

tests:
  GDHAPPI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GDHAPPI
